app/Modules/Users/User/Routes/admin.php
<?php
/**
 * Created by Maksym Ignatchenko, Appus Studio LP on 25.02.19
 *
 */

Route::group(['middleware' => 'auth:admin'], function () {
    Route::get('users/export', 'UserController@export')->name('users.export')->middleware('can:export,App\Modules\Users\User\Models\User');

    Route::post('users', 'UserController@store')->name('users.store')->middleware('can:create,App\Modules\Users\User\Models\User');
    Route::get('users', 'UserController@index')->name('users.index')->middleware('can:view,App\Modules\Users\User\Models\User');
    Route::get('users/create', 'UserController@create')->name('users.create')->middleware('can:create,App\Modules\Users\Admin\Models\Admin');
    Route::get('users/{user}/edit', 'UserController@edit')->name('users.edit')->middleware('can:edit,App\Modules\Users\User\Models\User');
    Route::get('users/{user}', 'UserController@show')->name('users.show')->middleware('can:view,App\Modules\Users\User\Models\User');

    Route::match(array('PATCH', 'PUT'), "users/{user}", array(
        'uses' => 'UserController@update',
        'as' => 'users.update'
    ))->middleware('can:edit,App\Modules\Users\User\Models\User');

    Route::put('reset-coins', 'UserController@resetAllCoins')
        ->name('reset-coins')
        ->middleware('can:resetTickets,App\Modules\Users\User\Models\User');

    Route::put('reset-coins-public-challenges', 'UserController@resetCoinsForPublicChallenges')
        ->name('reset-coins-public-challenges')
        ->middleware('can:resetTickets,App\Modules\Users\User\Models\User');

    Route::put('user-reset-coins/{user}', 'UserController@resetCoinsAndRating')
        ->name('user-reset-coins')
        ->middleware('can:resetTickets,App\Modules\Users\User\Models\User');

    Route::get('direct-user-send-notification/{user}', 'UserController@showUserNotificationForm')
        ->name('direct-user-notification-form')
        ->middleware('can:sendMessege,App\Modules\Users\User\Models\User');

    Route::post('direct-user-send-notification/{user}', 'UserController@sendNotification')
        ->name('direct-user-send-notification')
        ->middleware('can:sendMessege,App\Modules\Users\User\Models\User');

    Route::get('all-users-send-notification', 'UserController@showGroupOfUsersNotificationForm')
        ->name('all-users-notification-form')
        ->middleware('can:sendMessege,App\Modules\Users\User\Models\User');

    Route::post('all-users-send-notification', 'UserController@sendGroupNotification')
        ->name('all-users-send-notification')
        ->middleware('can:sendMessege,App\Modules\Users\User\Models\User');

    Route::post('users/{user_id}/suspend', 'UserController@suspend')->name('users.suspend')->middleware('can:suspend,App\Modules\Users\User\Models\User');
    Route::post('users/{user_id}/enable', 'UserController@enable')->name('users.enable')->middleware('can:enable,App\Modules\Users\User\Models\User');
});

app/Modules/Users/User/Routes/web.php
<?php
/**
 * Created by Artem Petrov, Appus Studio LP on 16.11.2017
 */

Route::group([
    'prefix' => 'password',
], function () {
    $this->get('reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    $this->post('reset', 'ResetPasswordController@reset')->name('password.restore');
    $this->get('success', 'ResetPasswordController@success')->name('password.success');
});

app/Modules/Users/User/Models/User.php
<?php

namespace App\Modules\Users\User\Models;

use App\Modules\Challenges\Enums\CountryEnum;
use App\Modules\Challenges\Enums\ProofStatusEnum;
use App\Modules\Challenges\Models\Challenge;
use App\Modules\Companies\Models\Company;
use App\Modules\Challenges\Models\Proof;
use App\Modules\Files\Services\ImageService;
use App\Modules\Notifications\Traits\Notifiable;
use App\Modules\Users\Services\ApiRatingData\Rankable;
use App\Modules\Users\Services\ReferralCodeService\ReferralAble;
use App\Modules\Users\Services\UserEnvironmentService\Enums\UserEnvironmentEnum;
use App\Modules\Users\Services\UserEnvironmentService\Interfaces\EnvironmentAble;
use App\Modules\Users\User\Mails\ResetPasswordMail;
use Exception;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Query\Builder as QueryBuilder;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Pagination\AbstractPaginator;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;
use Tymon\JWTAuth\Contracts\JWTSubject;
use Tymon\JWTAuth\Facades\JWTAuth;

class User extends Authenticatable implements JWTSubject, ReferralAble, CanGenerateJwtToken, Rankable, EnvironmentAble
{
    use Notifiable;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * @var integer
     */
    protected const DEFAULT_COINS_AMOUNT = 0;

    /**
     * @var null|integer
     */
    protected $total_reward;

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = [
        'birthday',
    ];

    /**
     * @var array
     */
    protected $with = [
        'company',
    ];

    protected $attributes = [
        'coins' => self::DEFAULT_COINS_AMOUNT,
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'full_name',
        'email',
        'password',
        'phone_number',
        'country_code',
        'is_registration_completed',
        'avatar',
        'birthday',
        'sex',
        'country',
        'city',
        'coins',
        'referral_code',
        'company_id',
        'status'
    ];

    protected $casts = [
        'is_registration_completed' => 'boolean',
        'birthday' => 'date:U',
        'created_at' => 'date:U',
        'updated_at' => 'date:U',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'facebook_id',
        'email_verified_at',
        'pivot',
        'company_id',
    ];

    /**
     * Get the identifier that will be stored in the subject claim of the JWT.
     *
     * @return mixed
     */
    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    /**
     * Return a key value array, containing any custom claims to be added to the JWT.
     *
     * @return array
     */
    public function getJWTCustomClaims()
    {
        return [];
    }

    /**
     * @param string $password
     */
    public function setPasswordAttribute(string $password): void
    {
        $this->attributes['password'] = Hash::make($password);
    }

    /**
     * Sends the password reset notification.
     *
     * @param string $token
     *
     * @return void
     */
    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ResetPasswordMail($token, $this));
    }

    /**
     * @return string
     */
    public function getAvatarAttribute($value): ?string
    {
        return $value ? Storage::url($value) : asset('/assets/images/default_avatar.png');
    }

    /**
     * @return string
     */
    public function getAvatarWithDefaultAttribute($value): ?string
    {
        return $value ? Storage::url($value) : asset('/assets/images/default_avatar.png');
    }

    /**
     * @return string|null
     */
    public function getDefaultAvatarAttribute(): ?string
    {
        return asset('/assets/images/default_avatar.png');
    }

    /**
     * @return string
     */
    public function getFullPhoneNumberAttribute(): string
    {
        return $this->country_code . $this->phone_number;
    }

    /**
     * @param $attribute
     */
    public function setAvatarAttribute($attribute)
    {
        $this->deleteAvatarFile();
        $path = 'avatars';
        $imageService = new ImageService($attribute);
        $image = $imageService->orientate();
        $fileName = $path . $attribute->hashName();
        Storage::put($fileName, $image);

        $this->attributes['avatar'] = $fileName;
    }

    protected function deleteAvatarFile(): void
    {
        if (null !== $this->getAvatarPath()) {
            Storage::delete($this->getAvatarPath());
        }
    }

    /**
     * @param $attribute
     */
    public function setCompanyIdAttribute($attribute)
    {
        $this->attributes['company_id'] = $attribute;
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function challenges()
    {
        return $this->belongsToMany(Challenge::class)->withTimestamps();
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function proofs()
    {
        return $this->hasMany(Proof::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function points()
    {
        return $this->hasMany(Point::class);
    }

    public function company()
    {
        return $this->belongsTo(Company::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function devices()
    {
        return $this->hasMany(Device::class);
    }

    /**
     * @return bool
     */
    public function enoughCoinsToParticipateChallenge(): bool
    {
        return $this->coins >= Challenge::PARTICIPATION_COST;
    }

    /**
     * @param Challenge $challenge
     * @return bool
     */
    public function isAbleToSendProof(Challenge $challenge): bool
    {
        return Proof::where('challenge_id', $challenge->id)
            ->where('user_id', $this->id)
            ->whereIn('status', [ProofStatusEnum::PENDING, ProofStatusEnum::ACCEPTED])
            ->count();

    }

    /**
     * @return string
     */
    public function getCountry(): string
    {
        return $this->country ?? CountryEnum::SAUDI_ARABIA;
    }

    /**
     * @return User
     */
    public function hideForPublic(): self
    {
        return $this->makeHidden([
            'updated_at_at',
            'phone_number',
            'country_code',
            'is_registration_completed',
            // 'coins',
        ]);
    }

    public function chargeReward(int $reward): void
    {
        $this->coins += $reward;
    }

    public function chargeRewardToReferralUser(): void
    {
        // TODO implement reward referral user after adding gold coins functionality
        // $referralUser = $this->where('referral_code', $this->referral_code)->first();
    }

    public function calculateReferralCode(): void
    {
        do {
            $randomCode = str_random(config('custom.referral_code_length'));
        } while ($this->where('referral_code', $randomCode)->first());
        $this->attributes['referral_code'] = str_random(config('custom.referral_code_length'));
    }

    /**
     * @return string
     */
    public function generateToken(): string
    {
        return JWTAuth::fromUser($this);
    }

    public function resetPublicCoinsAndRating(): void
    {
        //$this->points()->withoutCompanyPoints()->delete(); //todo: implement points
        $this->challenges()->each(function (Challenge $challenge) {
            $totalRewards = $challenge->proofs()->sum('reward');
            $this->coins = $this->coins - $totalRewards;
            $this->save();
            $challenge->proofs()->update(['reward' => 0]);
        });

        $this->update(['coins' => 0]);
    }

    public function resetPrivateCoinsAndRating(int $companyId): void
    {
        $this->company->challenges->each(function (Challenge $challenge) {
            $totalRewards = $challenge->proofs()->sum('reward');
            $this->coins = $this->coins - $totalRewards;
            $this->save();
            $challenge->proofs()->update(['reward' => 0]);
        });

        //$this->points()->forCompany($companyId)->delete(); //todo: implement points
        $this->save();
    }

    /**
     * @return AbstractPaginator
     */
    public function getRating(): AbstractPaginator
    {
        return $this->prepareRatingQuery()->paginate(config('custom.rating_results_count_per_page'));
    }

    protected function prepareRatingQuery(): Builder
    {
        $sub = $this->getRewardsSubqueryForEnvironment();

        return $this::joinSub($sub, 'rewards', function($join) {
            $join->on('users.id', '=', 'rewards.user_id');
        })
            ->select([
                'id',
                'full_name',
                'avatar',
                'rewards.total_reward',
                DB::raw('ROW_NUMBER() OVER(ORDER BY rewards.total_reward DESC, rewards.total_attempt_duration ASC) AS Position, rewards.total_reward'),
                'company_id'
            ]);
    }

    public function getLiveRating()
    {
        return $this->prepareLiveRatingQuery();
    }

    protected function prepareLiveRatingQuery(): Builder
    {
        $sub = $this->getRewardsSubqueryForEnvironment();

        return $this::joinSub($sub, 'rewards', function($join) {
            $join->on('users.id', '=', 'rewards.user_id');
        })
            ->select([
                'id',
                'full_name',
                'email',
                'phone_number',
                'country',
                'avatar',

app/Modules/Users/User/Resources/views/create.blade.php
@extends('layouts.app')
@section('title', 'Create user')
@section('content')

    <div class="content">
        <div class="clearfix"></div>
        @include('flash::message')
        <div class="clearfix"></div>
        {!! Form::open(['url'=> route('users.store'), 'method' => 'POST', 'files' => true]) !!}
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-body">
                        <h3 class="new_heading">Create User</h3>
                        @include('create_fields')
                    </div>
                </div>
            </div>
        </div>
        {!! Form::close() !!}
    </div>
@endsection

app/Modules/Users/User/Resources/views/create_fields.blade.php
<div class="row form-justify-container">
    <div class="col-md-6">
        <div class="box">
            <div class="box-body">
                <!-- Name Field -->
                <div class="form-group">
                    <p>
                        {{ Form::label('full_name', 'Full name: ') }}
                        {!! Form::text('full_name', null, ['class' => 'form-control', 'maxlength' => 100]) !!}
                    </p>
                    @if ($errors->has('full_name'))
                        <div class="text-red">{{ $errors->first('full_name') }}</div>
                    @endif
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="box">
            <div class="box-body">
                <!-- Email Field -->
                <div class="form-group">
                    <p>
                        {{ Form::label('email', 'Email: ') }}
                        {!! Form::text('email', null, ['class' => 'form-control', 'maxlength' => 50]) !!}
                    </p>
                    @if ($errors->has('email'))
                        <div class="text-red">{{ $errors->first('email') }}</div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row form-justify-container">
    <div class="col-md-6">
        <div class="box">
            <div class="box-body">
                <!-- Country Field -->
                <div class="form-group">
                    <p>
                        {{ Form::label('country_code', 'Country code: ',  ['class' => 'required']) }}
                        {!! Form::text('country_code', null, ['class' => 'form-control']) !!}
                    </p>
                    @if ($errors->has('country_code'))
                        <div class="text-red">{{ $errors->first('country_code') }}</div>
                    @endif
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="box">
            <div class="box-body">
                <!-- Country Field -->
                <div class="form-group">
                    <p>
                        {{ Form::label('phone_number', 'Phone number: ',  ['class' => 'required']) }}
                        {!! Form::text('phone_number', null, ['class' => 'form-control']) !!}
                    </p>
                    @if ($errors->has('phone_number'))
                        <div class="text-red">{{ $errors->first('phone_number') }}</div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row form-justify-container">
    <div class="col-md-6">
        <div class="box">
            <div class="box-body">
                <!-- Country Field -->
                <div class="form-group">
                    <p>
                        {{ Form::label('country', 'Country: ') }}
                        {!! Form::select('country', App\Modules\Users\User\Models\User::getCountriesList(), null, ['class' => 'form-control select2']) !!}
                    </p>
                    @if ($errors->has('country'))
                        <div class="text-red">{{ $errors->first('country') }}</div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row form-justify-container">
    <div class="col-md-6">
        <div class="box">
            <div class="box-body">
                <!-- Country Field -->
                <div class="form-group">
                    <p>
                        {{ Form::label('password', 'Password: ',  ['class' => 'required']) }}
                        {!! Form::password('password', ['class' => 'form-control']) !!}
                    </p>
                    @if ($errors->has('password'))
                        <div class="text-red">{{ $errors->first('password') }}</div>
                    @endif
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="box">
            <div class="box-body">
                <!-- Country Field -->
                <div class="form-group">
                    <p>
                        {{ Form::label('password_confirmation', 'Password confirm: ',  ['class' => 'required']) }}
                        {!! Form::password('password_confirmation', ['class' => 'form-control']) !!}
                    </p>
                    @if ($errors->has('password_confirmation'))
                        <div class="text-red">{{ $errors->first('password_confirmation') }}</div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Submit Field -->
<div class="form-group text-left">
    {!! Form::submit('Create', ['class' => 'btn btn-primary waves-effect waves-light']) !!}
</div>

<script>
$(document).ready(function(){
    $('.select2').select2({
        theme: 'bootstrap',
        width: '100%'
    });
});
</script>

app/Modules/Users/User/Resources/views/datatables_actions.blade.php
<div class="btn-group" role="group">
    <button id="btnGroupDrop1" type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Actions
    </button>
    <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
        <a href="{{ route('users.show', $id) }}" class='dropdown-item'>
            Show
        </a>
        <a href="{{ route('users.edit', $id) }}" class='dropdown-item'>
            Edit
        </a>
        <a href="{{ route('direct-user-send-notification', $id) }}" class='dropdown-item'>
            Send message
        </a>
        <a href="#" class='dropdown-item'
           onclick="document.getElementById('reset-{{$id}}-button').click()">
            {!! Form::open(['method'=>'PUT', 'url'=> route('user-reset-coins', $id)]) !!}
            <button style="display: none;" id="reset-{{$id}}-button" data-toggle="tooltip" data-placement="top" title="Reset points and rating"
                    type="submit" class="dropdown-item"
                    onclick="return confirm('Are you sure you want reset user\'s points?');">
            </button>
            {!! Form::close() !!}
            Reset points and rating
        </a>
        @php $user = \App\Modules\Users\User\Models\User::find($id) @endphp
        @if($user->status == '1')
        <a href="#" class='dropdown-item'
        onclick="document.getElementById('suspend-{{$id}}-button').click()">
            {!! Form::open(['method'=>'POST', 'url'=> route('users.suspend', $id)]) !!}
            <button style="display: none;" id="suspend-{{$id}}-button" data-toggle="tooltip" data-placement="top" title="Suspend"
                    type="submit" class="dropdown-item"
                    onclick="return confirm('Are you sure you want suspend this reset user?');">
            </button>
            {!! Form::close() !!}
            Suspend
        </a>
        @endif

        @if($user->status == '2')
        <a href="#" class='dropdown-item'
        onclick="document.getElementById('enable-{{$id}}-button').click()">
            {!! Form::open(['method'=>'POST', 'url'=> route('users.enable', $id)]) !!}
            <button style="display:none" id="enable-{{$id}}-button" data-toggle="tooltip" data-placement="top" title="Enable"
                    type="submit" class="dropdown-item"
                    onclick="return confirm('Are you sure you want to enable this user?');">
            </button>
            {!! Form::close() !!}
            Enable
        </a>
        @endif
    </div>
</div>

app/Modules/Users/User/Resources/views/edit.blade.php
@extends('layouts.app')
@section('title', 'Edit user')
@section('content')

    <div class="content">
        <div class="clearfix"></div>
        @include('flash::message')
        <div class="clearfix"></div>
        {!! Form::open(['url'=> route('users.update', ['usert' => $dto->getUserId()]), 'method' => 'PUT', 'files' => true]) !!}
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-body">
                        <h3 class="new_heading">Edit User</h3>
                        @include('edit_fields')
                    </div>
                </div>
            </div>
        </div>
        {!! Form::close() !!}
    </div>
@endsection

app/Modules/Users/User/Resources/views/index.blade.php
@extends('layouts.app')
@section('title', 'Users')

@section('content')
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box">
            <div class="box-body">
                    <h3 class="new_heading">Manage Users</h3>
                    <div class="buttons-group">
                        <div>
                            <a href="#" class='btn btn-danger create-article'
                               onclick="document.getElementById('reset-coins').click()">
                                {!! Form::open(['method'=>'PUT', 'url'=> route('reset-coins')]) !!}
                                <button hidden id="reset-coins" data-toggle="tooltip" data-placement="top" title="Reset coins for all users"
                                        type="submit" class="dropdown-item"
                                        onclick="return confirm('Are you sure you want reset points for all users?');">
                                </button>
                                {!! Form::close() !!}
                                Reset all points
                            </a>
                        </div>
                        <div>
                            <a href="#" class='btn btn-warning create-article'
                               onclick="document.getElementById('reset-coins-public-challenges').click()">
                                {!! Form::open(['method'=>'PUT', 'url'=> route('reset-coins-public-challenges')]) !!}
                                <button hidden id="reset-coins-public-challenges" data-toggle="tooltip" data-placement="top"
                                        title="Reset coins for all public challenges"
                                        type="submit" class="dropdown-item"
                                        onclick="return confirm('Are you sure you want reset points for all public challenges?');">
                                </button>
                                {!! Form::close() !!}
                                Reset points for public challenges
                            </a>
                        </div>
                        <div>
                            <a href="{{ route('all-users-notification-form') }}" class='btn btn-primary'>
                                Send message to all users
                            </a>
                        </div>
                        <div>
                            <a href="{{ route('users.export', ['type' => 'csv']) }}" class='btn btn-primary'>
                                Export to csv
                            </a>
                        </div>
                        <div>
                            <a href="{{ route('users.create') }}" class='btn btn-primary'>
                                Create user
                            </a>
                        </div>
                    </div>
                @include('table')
            </div>
        </div>
    </div>
@endsection

app/Modules/Users/User/Resources/views/message.blade.php
@extends('layouts.app')
@section('title', $dto->getPageTitle())
@section('content')

    <div class="content">

        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>

        {!! Form::open(['url'=> $dto->getFormAction(), 'method' => 'POST']) !!}
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-body">
                        <!-- Title Field -->
                        <div class="form-group">
                            {!! Form::label('title', 'Title ') !!}
                            {!! Form::text('title', $dto->getDefaultTitle(), ['class' => 'form-control', 'maxlength' => $dto->getTitleLimitSize()]) !!}
                            @if ($errors->has('title'))
                                <div class="alert alert-danger" role="alert"><strong>{{ $errors->first('title') }}</strong></div>
                            @endif
                        </div>

                        <!-- Message Field -->
                        <div class="form-group">
                            {!! Form::label('message', 'Message ') !!}
                            {!! Form::textarea('message', null, ['class' => 'form-control', 'id' => 'message', 'maxlength' => $dto->getMessageLimitSize()]) !!}
                            @if ($errors->has('message'))
                                <div class="alert alert-danger" role="alert"><strong>{{ $errors->first('message') }}</strong></div>
                            @endif
                        </div>

                        @if($dto->isNeedFilters())
                            <!-- Country Field -->
                                <div class="form-group">
                                    {!! Form::label('country', 'Country ') !!}
                                    {!! Form::select('country', App\Modules\Users\User\Models\User::getCountriesList(), old('country'), ['class' => 'form-control']) !!}
                                    @if ($errors->has('country'))
                                        <div class="alert alert-danger" role="alert"><strong>{{ $errors->first('country') }}</strong></div>
                                    @endif
                                </div>
                        @endif

                        <!-- Submit Field -->
                        <div class="form-group text-left">
                            {!! Form::submit('Send', ['class' => 'btn btn-primary waves-effect waves-light']) !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {!! Form::close() !!}

    </div>
@endsection

app/Modules/Users/User/Resources/views/show.blade.php
@extends('layouts.app')
@section('title', 'User details')
@section('content')

    <div class="content">

        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>

        <div class="row">

            <div class="col-md-12">
                <div class="box">
                    <div class="box-body">
                        @include('show_fields')
                    </div>
                </div>
            </div>
        </div>

    </div>
@endsection

app/Modules/Users/User/Resources/views/show_fields.blade.php
<div class="row">
    <div class="col-sm-2">
        <div class="media">
            <img class="d-flex mr-3 rounded-circle img-thumbnail thumb-lg" src="{{$user->avatar ?? $user->avatar_with_default}}" alt="Generic placeholder image">
        </div>
        <p>&nbsp;</p>
        <!-- Edit Button -->
        <div class="form-group text-left">
            <a href="{{ route('users.edit', $user->id) }}" class="btn btn-primary waves-effect waves-light">Go to edit user</a>
        </div>
    </div>
    <div class="col-sm-6">
        <table class="table table-striped">
            <tr>
                <th width='30%'>Full name</th>
                <td>{{$user->full_name}}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{$user->email}}</td>
            </tr>
            <tr>
                <th>Phone number</th>
                <td><span class="{{$user->full_phone_number ? '' : 'text-danger'}}">{{ $user->full_phone_number ?? 'Empty' }}</span></td>
            </tr>
            <tr>
                <th>Country</th>
                <td><span class="{{$user->country ? '' : 'text-danger'}}">{{ $user->country ?? 'Empty' }}</span></td>
            </tr>
            <tr>
                <th>Date of Birth</th>
                <td><span class="{{$user->birthday ? '' : 'text-danger'}}">{{ $user->birthday ? $user->birthday->format('y-m-d') : 'Empty' }}</span></td>
            </tr>
            <tr>
                <th>Sex</th>
                <td><span class="{{$user->sex ? '' : 'text-danger'}}">{{ $user->sex ?? 'Empty' }}</span></td>
            </tr>
            <tr>
                <th>City</th>
                <td><span class="{{$user->city ? '' : 'text-danger'}}">{{ $user->city ?? 'Empty' }}</span></td>
            </tr>
            <tr>
                <th>Company</th>
                <td>
                    @if($user->company)
                        <a href="{{ route('company.show', $user->company->id) }}">
                            {{ $user->company->name }}
                        </a>
                    @else
                    <span class="text-danger">
                        Empty
                    </span>
                    @endif
                </td>
            </tr>
        </table>

    </div>
</div>

app/Modules/Users/User/Resources/views/table.blade.php
{!! $dataTable->table(['width' => '100%']) !!}

@section('script')
    {!! $dataTable->scripts() !!}
@endsection